version: '3'

services:
  logstash:
    build:
      context: ./logstash/
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./logstash/pipeline.conf:/usr/share/logstash/pipeline/logstash.conf:ro
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    depends_on: [vlogs]
    ports:
      - "5140:5140"

  # Run `make package-victoria-logs` to build victoria-logs image
  vlogs:
    image: docker.io/victoriametrics/victoria-logs:heads-logs-examples-0-g66b42a677-dirty-b95f1d4b
    volumes:
      - vlogs:/vlogs
    ports:
      - "9428:9428"
    command:
      - -storageDataPath=/vlogs

volumes:
  vlogs:
