version: '3'

services:
  filebeat-victorialogs:
    image: docker.elastic.co/beats/filebeat:8.8.1
    restart: on-failure
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/containers/
        target: /var/lib/docker/containers/
      - ./victorialogs/config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    user: root
    command:
      - "--strict.perms=false"
    depends_on: [ victorialogs ]
  beat-exporter-victorialogs:
    image: trustpilot/beat-exporter:0.4.0
    command:
      - -beat.uri=http://filebeat-victorialogs:5066

  # Run `make package-victoria-logs` to build victoria-logs image
  victorialogs:
    image: docker.io/victoriametrics/victoria-logs:heads-master-0-g88993f312-dirty-e01fb71f
    volumes:
      - victorialogs-vl:/vlogs
    ports:
      - '9428:9428'
    command:
      - -storageDataPath=/vlogs
      - -loggerFormat=json
  grafana:
    container_name: grafana
    image: grafana/grafana:9.2.7
    depends_on:
      - "victoriametrics"
    ports:
      - 3000:3000
    volumes:
      - victorialogs-grafana:/var/lib/grafana
      - ./provisioning/:/etc/grafana/provisioning/
      - ./../../dashboards/victoriametrics.json:/var/lib/grafana/dashboards/vm.json
      - ./victorialogs/dashboard.json:/var/lib/grafana/dashboards/vl-for-docker.json
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.91.2
    ports:
      - '8428:8428'
    command:
      - -storageDataPath=/vmsingle
      - -promscrape.config=/promscrape.yml
      - -loggerFormat=json
    volumes:
      - victorialogs-vm:/vmsingle
      - ./victorialogs/config/scrape.yml:/promscrape.yml

volumes:
  victorialogs-vl:
  victorialogs-vm:
  victorialogs-grafana:
