version: "3"

services:
  fluentbit:
    image: cr.fluentbit.io/fluent/fluent-bit:2.1.4
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    depends_on: [vlogs]
    ports:
      - "5140:5140"

  # Run `make package-victoria-logs` to build victoria-logs image
  vlogs:
    image: docker.io/victoriametrics/victoria-logs:heads-logs-examples-0-g66b42a677-dirty-b95f1d4b
    volumes:
      - vlogs:/vlogs
    ports:
      - "9428:9428"
    command:
      - -storageDataPath=/vlogs

volumes:
  vlogs:
