name: nightly-build
on:
  schedule:
    # Daily at 2:48am
    - cron: '48 2 * * *'
  push:
    branches:
      - update-vulnerability-scan

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup Go
        uses: actions/setup-go@main
        with:
          go-version: 1.20.4
        id: go

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Code checkout
        uses: actions/checkout@master

      - uses: actions/cache@v3
        with:
          path: gocache-for-docker
          key: gocache-docker-${{ runner.os }}-${{ steps.go.outputs.go-version }}-${{ hashFiles('go.mod') }}

      - name: setup snyk
        uses: snyk/actions/setup@master

      - name: build & publish
        run: |
          LATEST_TAG=nightly PKG_TAG=nightly make publish
        env: 
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload result to GitHub Code Scanning
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./snyk
